const products = {
 categories: [[1,'Visiting Cards'],[5,'Custom Polo T-shirts'],[10,'Custom Dress Shirts'],[6,'Custom T-shirts'],[11,'Custom Winter Wear'],[2,'Custom Caps'],[0,'Signs, Posters & Marketing Materials'],[7,'Custom Stamps & Ink']],
 popular: [[17,'Standard Visiting Cards','100','200'],[81,'Rounded Corner Visiting Cards','100','250'],[61,'Letterheads','10','230'],[62,'Photo Albums','1','175'],[37,'Stickers','10','150'],[76,'Hoodies','1','1030'],[59,'Embroidered Caps','1','310']],
 trending: [[73,'Classic Visiting Cards','100','230'],[18,'Spot UV Visiting Cards','100','580'],[69,"Men’s Puffer Jacket",'1','2450'],[59,'Embroidered Caps','1','310'],[68,'Premium Polo T-Shirts','1','800'],[80,'Printed Polos - Multi Location','1','590'],[63,'Winter Jacket - Sleeveless','1','1275']],
 labels: [[40,'Sheet Stickers','24','190'],[34,'Product & Packaging Labels','24','160'],[36,'Custom Shape Stickers','10','190'],[41,'Sticker Singles','50','245'],[86,'Self Adhesive Tapes','6','6600'],[42,'Transparent Labels','40','400'],[37,'Stickers','10','150']],
 explore: [[63,'Winter Jacket - Sleeveless','1','1275'],[25,'Embroidered Laptop Bags','1','1050'],[19,'Harissons® Nemesis Office Laptop Bags','1','1370'],[28,'Diary With Pen Holder','1','465'],[30,'Lanyards','10','740'],[23,'Brochures','25','430'],[62,'Photo Albums','1','175']],
 arrivals: [[48,'Custom Document Files','5','250'],[53,'Translite Board','1','1500'],[45,'American Tourister® TROT 3.0 Laptop Backpacks','1','3800'],[52,'Full-Print Mailer Boxes','500','15750'],[56,'Swiss Military® Zipper Hoodies','1','2200'],[49,'Custom Full White Ball Pens','50','1500'],[25,'Embroidered Laptop Bags','1','1050']]
};
const titles={categories:'Explore all categories',popular:'Our Most Popular Products',trending:'Trending',labels:'Labels, Stickers and Packaging',explore:'Explore More',arrivals:'New Arrivals'};
const productPaths={1:'visiting-cards',17:'visiting-cards/standard',81:'visiting-cards/rounded-corner',73:'visiting-cards/classic',18:'visiting-cards/spot-uv',61:'stationery/letterheads',62:'photo-gifts/photo-books',37:'labels-stickers',5:'clothing-bags/polo-t-shirts',10:'clothing-bags/dress-shirts',6:'clothing-bags/t-shirts',11:'clothing-bags/winter-wear',2:'clothing-bags/caps',0:'signs-posters',7:'stamps',40:'labels-stickers/sheet-stickers',34:'labels-stickers/product-labels',36:'labels-stickers/custom-shape-stickers',41:'labels-stickers/sticker-singles',86:'packaging/self-adhesive-tapes',42:'labels-stickers/transparent-labels'};
function productUrl(p){return 'https://www.vistaprint.in/'+(productPaths[p[0]]||'search?query='+encodeURIComponent(p[1]));}
function section(key){const s=document.createElement('section');s.className='catalog-section '+key;s.id=key;s.setAttribute('aria-labelledby',key+'-title');s.innerHTML=`<h2 id="${key}-title">${titles[key]}</h2><div class="rail-wrap"><div class="product-rail">${products[key].map(p=>`<a class="product-card" href="${productUrl(p)}" data-name="${p[1].toLowerCase()}"><div class="product-image">${p[2]?`<span class="price-tag">BUY ${p[2]} @ Rs.${p[3]}</span>`:''}<img src="assets/image-${p[0]}.jpg" alt="${p[1]}" loading="lazy" width="450" height="450"></div><h3>${p[1]}</h3></a>`).join('')}</div><button class="rail-next" aria-label="Show more ${titles[key]}">›</button></div>`;s.querySelector('.rail-next').addEventListener('click',()=>{const rail=s.querySelector('.product-rail');if(rail.scrollLeft+rail.clientWidth>=rail.scrollWidth-5)rail.scrollTo({left:0});else rail.scrollBy({left:rail.clientWidth*.75});});return s;}
['categories','popular','trending','labels'].forEach(k=>document.getElementById('top-sections').append(section(k)));['explore','arrivals'].forEach(k=>document.getElementById('bottom-sections').append(section(k)));
const navItems=[['View All','categories'],['Visiting Cards','popular'],['Stationery, Letterheads & Notebooks','popular'],['Stamps and Ink','categories'],['Signs, Posters & Marketing Materials','categories'],['Labels, Stickers & Packaging','labels'],['Clothing, Caps & Bags','trending'],['Mugs, Albums & Gifts','popular'],['Pens','arrivals'],['Drinkware','explore'],['Custom Polo T-shirts','trending'],['Custom Winterwear','trending']];document.getElementById('main-nav').innerHTML=navItems.map(([name,id])=>`<a href="#${id}">${name}</a>`).join('');
const toggle=document.querySelector('.mobile-toggle');toggle.addEventListener('click',()=>{const open=document.getElementById('main-nav').classList.toggle('open');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.getElementById('main-nav').classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
let toastTimer;function toast(message){const el=document.getElementById('toast');el.textContent=message;el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',3500)}
document.getElementById('copy-code').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('SAVES');toast('Discount code SAVES copied!')}catch{toast('Use code SAVES at checkout')}});
const search=document.getElementById('search');function filterProducts(){const q=search.value.trim().toLowerCase();let count=0;document.querySelectorAll('.catalog-section').forEach(section=>{let matches=0;section.querySelectorAll('.product-card').forEach(card=>{card.hidden=!!q&&!card.dataset.name.includes(q);if(!card.hidden)matches++});section.hidden=!!q&&!matches;section.querySelector('.rail-next').hidden=!!q;count+=matches});const status=document.getElementById('search-status');status.hidden=!q;status.textContent=count?`${count} matching products for “${search.value.trim()}”. Clear search to explore all products.`:`No products found for “${search.value.trim()}”. Try cards, shirts, stickers or bags.`;if(q)status.scrollIntoView({behavior:'smooth',block:'start'})}document.getElementById('search-form').addEventListener('submit',e=>{e.preventDefault();filterProducts()});search.addEventListener('input',()=>{if(!search.value)filterProducts()});
const email=document.getElementById('email');const submit=document.querySelector('.submit-button');email.addEventListener('input',()=>submit.disabled=!email.validity.valid||!email.value);document.getElementById('newsletter-form').addEventListener('submit',e=>{e.preventDefault();document.getElementById('newsletter-message').textContent='This is a frontend preview. Email subscriptions are not connected yet.'});
const panels={favourites:['My Favorites','Your favorite products will appear here. Explore our products to find something you love.'],cart:['Your cart is empty','Find your next great idea in our popular products.'],signin:['Welcome to VistaPrint','Continue to the official VistaPrint website to sign in to your account.']};document.querySelectorAll('[data-panel]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.panel;document.getElementById('modal-title').textContent=panels[key][0];document.getElementById('modal-body').innerHTML=`<p>${panels[key][1]}</p><a class="btn btn-dark" href="${key==='signin'?'https://www.vistaprint.in/my-account/':'#popular'}" ${key==='signin'?'':'data-bs-dismiss="modal"'}>${key==='signin'?'Continue to VistaPrint':'Explore products'}</a>`;new bootstrap.Modal(document.getElementById('info-modal')).show()}));
